In [1]:
import numpy as np

In [2]:
l=[45,7,9,3,678,3,43,5]
n=np.array(l)
n

array([ 45,   7,   9,   3, 678,   3,  43,   5])

In [3]:
l=[5.3,89,358,58,4]
n=np.array(l)
print(n)

[  5.3  89.  358.   58.    4. ]


In [4]:
l=[5,89,358,58,4]
n=np.asarray(l,dtype='float32')
print(n)

[  5.  89. 358.  58.   4.]


In [5]:
 n= np.array([range(i, i + 3) for i in [2, 4, 6]])
print(n)
print(n[0,1],n[2,1])

[[2 3 4]
 [4 5 6]
 [6 7 8]]
3 7


In [6]:
print(n.shape)

(3, 3)


In [7]:
print(n.dtype)

int64


In [8]:
n[2,0]=90
print(n)

[[ 2  3  4]
 [ 4  5  6]
 [90  7  8]]


In [9]:
print(n.size)

9


In [10]:
dic=np.array({34,632,678})
print(dic)
print(dic.dtype)
print(type(dic))

{632, 34, 678}
object
<class 'numpy.ndarray'>


In [11]:
zero=np.zeros((2,5))
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
aran=np.arange(13)
print(aran) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
lspace=np.linspace(1,10,10,dtype='float32')
lspace2=np.linspace(1,50,10,dtype='float32')
print(lspace)
print(lspace2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.         6.4444447 11.888889  17.333334  22.777779  28.222221
 33.666668  39.11111   44.555557  50.       ]


In [14]:
emp=np.empty((4,5))
print(emp)

[[0.00000000e+000 0.00000000e+000 3.84081238e-312 3.92569221e-312
  8.72100932e+183]
 [1.00341853e-311 3.44618852e-085 1.00341853e-311 3.98837290e+252
  1.00341853e-311]
 [9.48694547e+170 1.00341853e-311 4.82406433e+228 1.00341853e-311
  2.28133101e+161]
 [1.00341853e-311 2.87302937e+161 1.00341853e-311 7.20637607e+252
  1.00341853e-311]]


In [15]:
emp2=np.empty_like(lspace2)
print(emp2)

[ 1.         6.4444447 11.888889  17.333334  22.777779  28.222221
 33.666668  39.11111   44.555557  50.       ]


In [16]:
idt=np.identity(4)
idt

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
a=np.arange(60)
a=a.reshape(4,15)
print (a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]]


In [18]:
a=a.ravel()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [19]:
arr=np.array([range(i, i + 3) for i in [2, 4, 6]])
print(arr.sum(axis=0))
arr.sum(axis=1)

[12 15 18]


array([ 9, 15, 21])

In [20]:
arr.T

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [21]:
for i in arr.flat:
    print(i)

2
3
4
4
5
6
6
7
8


In [22]:
arr.ndim

2

In [23]:

arr.nbytes

72

In [24]:
n.argmax()

np.int64(6)

In [25]:
n.argmin()

np.int64(0)

In [26]:
print(n)
n.argsort()

[[ 2  3  4]
 [ 4  5  6]
 [90  7  8]]


array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]])

In [27]:
arr.argmax()

np.int64(8)

In [28]:
arr.argmin()

np.int64(0)

In [29]:
arr.argmax(axis=0) 

array([2, 2, 2])

In [30]:
arr.argmax(axis=1) 

array([2, 2, 2])

In [31]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [32]:
arr


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [33]:
arr1=np.array([[6,3,8],[8,3,9],[1,4,7]])
arr1

array([[6, 3, 8],
       [8, 3, 9],
       [1, 4, 7]])

In [34]:
arr+arr1

array([[ 8,  6, 12],
       [12,  8, 15],
       [ 7, 11, 15]])

In [35]:
arr*arr1

array([[12,  9, 32],
       [32, 15, 54],
       [ 6, 28, 56]])

In [36]:
np.sqrt(arr1)

array([[2.44948974, 1.73205081, 2.82842712],
       [2.82842712, 1.73205081, 3.        ],
       [1.        , 2.        , 2.64575131]])

In [37]:
arr1.sum()

np.int64(49)

In [38]:
print(np.where(arr1>6))

(array([0, 1, 1, 2]), array([2, 0, 2, 2]))


In [39]:
np.nonzero(arr1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [40]:
np.count_nonzero(arr1)

9

In [41]:
import numpy as np
a = np.array([1, 2, 3], dtype=complex)
print(a) 

[1.+0.j 2.+0.j 3.+0.j]


In [42]:
dt=np.dtype(np.int32)
print (dt)

int32


In [43]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4',etc.

In [44]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype=dt)
print( a['age'])
a['age']
a

[10 20 30]


array([(10,), (20,), (30,)], dtype=[('age', 'i1')])

In [45]:
dt=np.dtype([('age',np.int8),('marks',np.float16)])
student=np.array([[45,16,45],[54,17,46],[45,13,34]],dtype=dt)
print(student)
student

[[(45, 45.) (16, 16.) (45, 45.)]
 [(54, 54.) (17, 17.) (46, 46.)]
 [(45, 45.) (13, 13.) (34, 34.)]]


array([[(45, 45.), (16, 16.), (45, 45.)],
       [(54, 54.), (17, 17.), (46, 46.)],
       [(45, 45.), (13, 13.), (34, 34.)]],
      dtype=[('age', 'i1'), ('marks', '<f2')])

In [46]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
import numpy as np
x = np.array([1,2,3,4,5], dtype=np.int8)
print  ( x.itemsize)
print(x.flags)
x.size

1
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



5

In [48]:
x = np.zeros((3,3), dtype=[('x', 'i4'), ('y', 'i4')])
print(x)

[[(0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0)]]


In [49]:
x=np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [50]:
x=np.ones([3,5])
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
list = range(5)
it = iter(list)
x = np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [53]:
s = b'Hello World'
a = np.frombuffer(s,dtype='S1')
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [54]:
e = np.full((2,6),7)
e

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [55]:
f = np.eye(7) 
f

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [56]:
a=np.random.random((4,6))
print(a)
print(a.T)

[[0.9716283  0.95812298 0.54460881 0.60249746 0.03934886 0.98602896]
 [0.67013177 0.61712666 0.09507951 0.48785876 0.44828477 0.32928553]
 [0.86838054 0.07845637 0.34257797 0.68317157 0.98848498 0.71506215]
 [0.16798734 0.80509193 0.34449235 0.69964268 0.85738508 0.14655036]]
[[0.9716283  0.67013177 0.86838054 0.16798734]
 [0.95812298 0.61712666 0.07845637 0.80509193]
 [0.54460881 0.09507951 0.34257797 0.34449235]
 [0.60249746 0.48785876 0.68317157 0.69964268]
 [0.03934886 0.44828477 0.98848498 0.85738508]
 [0.98602896 0.32928553 0.71506215 0.14655036]]


In [57]:
a=np.random.randint(0,10,10)
print(np.sin(a))
print(np.cos(a))
print(np.log(a))
print(np.exp(a))
print(np.sqrt(a))

[ 0.98935825  0.90929743  0.6569866  -0.2794155   0.98935825 -0.2794155
 -0.2794155   0.41211849  0.84147098 -0.95892427]
[-0.14550003 -0.41614684  0.75390225  0.96017029 -0.14550003  0.96017029
  0.96017029 -0.91113026  0.54030231  0.28366219]
[2.07944154 0.69314718 1.94591015 1.79175947 2.07944154 1.79175947
 1.79175947 2.19722458 0.         1.60943791]
[2.98095799e+03 7.38905610e+00 1.09663316e+03 4.03428793e+02
 2.98095799e+03 4.03428793e+02 4.03428793e+02 8.10308393e+03
 2.71828183e+00 1.48413159e+02]
[2.82842712 1.41421356 2.64575131 2.44948974 2.82842712 2.44948974
 2.44948974 3.         1.         2.23606798]


In [58]:
n=np.array([[2,4,1],[6,4,9],[8,25,0]],dtype='int16')
n

array([[ 2,  4,  1],
       [ 6,  4,  9],
       [ 8, 25,  0]], dtype=int16)

In [ ]:
print(n.argmax())
print(n.argmin())
print(n.max())
print(n.min())

7
8
25
0


In [60]:
print(n.argsort())
print(n)

[[2 0 1]
 [1 0 2]
 [2 0 1]]
[[ 2  4  1]
 [ 6  4  9]
 [ 8 25  0]]


In [61]:
print(n.argsort(axis=0))
print(n.argsort(axis=1))
print(n)

[[0 0 2]
 [1 1 0]
 [2 2 1]]
[[2 0 1]
 [1 0 2]
 [2 0 1]]
[[ 2  4  1]
 [ 6  4  9]
 [ 8 25  0]]


In [62]:
print(n.sum())
print(n.sum(axis=0))
print(n.sum(axis=1))

59
[16 33 10]
[ 7 19 33]


In [63]:
n.sort(axis=0)
n

array([[ 2,  4,  0],
       [ 6,  4,  1],
       [ 8, 25,  9]], dtype=int16)

In [64]:
mat=np.matrix([[ 1,  2,  4],[ 4,  6,  9],[ 0,  8, 25]])
mat1=np.matrix([[ 8,  3,  1],[ 2,  1,  7],[ 6,  2, 5]])
print(type(mat))
print(mat.dot(mat1))
print(mat.transpose())

<class 'numpy.matrix'>
[[ 36  13  35]
 [ 98  36  91]
 [166  58 181]]
[[ 1  4  0]
 [ 2  6  8]
 [ 4  9 25]]


In [65]:
mat1=np.matrix([[ 8,  3,  1],[ 2,  1,  7],[ 6,  2, 5]])
print(np.linalg.inv(mat1))
print(np.linalg.matrix_power(mat1,4))
print(np.linalg.matrix_power(mat1,0))
print(np.linalg.matrix_power(mat1,-4))
print(np.linalg.det(mat1))
mat1

[[-0.40909091 -0.59090909  0.90909091]
 [ 1.45454545  1.54545455 -2.45454545]
 [-0.09090909  0.09090909  0.09090909]]
[[10304  3833  5390]
 [ 9428  3501  4944]
 [11722  4358  6133]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[-0.31725548 -0.07756045  0.34134451]
 [ 0.5619664   0.05486306 -0.53811215]
 [ 0.20704699  0.10925654 -0.26987569]]
22.000000000000004


matrix([[8, 3, 1],
        [2, 1, 7],
        [6, 2, 5]])

In [ ]:
var=np.array([1,2,4,3,5])
np.insert(var,3,45)
np.insert(var,(3,5),45) 

array([ 1,  2,  4, 45,  3,  5, 45])

In [67]:
mat1=np.array([[ 8,  3],[ 2,  1],[ 6,  5]])
print(np.insert(mat1,2,1,axis=0))
print()
print(np.insert(mat1,2,[2,3],axis=0))
print()
print(np.insert(mat1,2,[2,3,4],axis=1))
print()
print(np.insert(mat1,2,1,axis=1))
print()
print(np.delete(mat1,4))
print()
print(np.delete(mat1,0,axis=0))
np.delete(mat1,0,axis=1)

[[8 3]
 [2 1]
 [1 1]
 [6 5]]

[[8 3]
 [2 1]
 [2 3]
 [6 5]]

[[8 3 2]
 [2 1 3]
 [6 5 4]]

[[8 3 1]
 [2 1 1]
 [6 5 1]]

[8 3 2 1 5]

[[2 1]
 [6 5]]


array([[3],
       [1],
       [5]])

In [68]:
import random 
v=np.random.rand(5,3)
v4=np.random.randn(5,3)
v1=np.random.randn(5)
v2=np.random.ranf(5)
v3=np.random.randint(1,20,4)
print(v)
print(v1)
print(v2)
print(v4)
print(v3)

[[0.63991345 0.50398371 0.55880608]
 [0.72765956 0.89763325 0.96490552]
 [0.11896297 0.24061341 0.78392467]
 [0.24602738 0.67673091 0.5322285 ]
 [0.1795291  0.55050421 0.42226202]]
[-0.42066734 -0.10061261  0.79230689 -0.06868638 -0.89629896]
[0.31622493 0.50794911 0.32325429 0.19373248 0.43745734]
[[-0.51554515  0.26070581 -0.12079353]
 [-0.10015241  0.91169018 -0.14110863]
 [ 2.01854198  0.45574356 -0.76297813]
 [ 0.577119   -1.05205943 -0.72973396]
 [-0.40030012 -1.65124903 -1.08446145]]
[13  6 13  4]


In [69]:
v=np.array([[19 ,4 ,10,12],[5,  7 , 4, 19],[ 2, 12 ,8,  7]])
print(v[0,1:])
print(v[2,2:3])

[ 4 10 12]
[8]


In [70]:
v=np.array([[19 ,4 ,10,12],[5,  7 , 4, 19],[ 2, 12 ,8,  7]])
for i in np.nditer(v):
    print(i,end='')
print('\n')
for i in v.flat:
    print(i,end='')
print('\n')
for i in v:
    for j in i:
        print(j,end='')
print()
print()
for i,j in np.ndenumerate(v):
    print(i,j)

19410125741921287

19410125741921287

19410125741921287

(0, 0) 19
(0, 1) 4
(0, 2) 10
(0, 3) 12
(1, 0) 5
(1, 1) 7
(1, 2) 4
(1, 3) 19
(2, 0) 2
(2, 1) 12
(2, 2) 8
(2, 3) 7


In [71]:
v=np.array([[19,4],[5,8],[2,7]],dtype='int16')
mat1=np.array([[8,3],[2,1],[6,5]],dtype='int16')
print(np.concatenate([mat1,v],axis=1))
print(np.concatenate([mat1,v],axis=0))  

[[ 8  3 19  4]
 [ 2  1  5  8]
 [ 6  5  2  7]]
[[ 8  3]
 [ 2  1]
 [ 6  5]
 [19  4]
 [ 5  8]
 [ 2  7]]


In [72]:
print(np.random.random((3, 3)))
np.random.rand(3, 3)

[[0.99959153 0.15202803 0.63684717]
 [0.16803032 0.56870548 0.32604305]
 [0.41031256 0.38752037 0.75653394]]


array([[0.54669423, 0.20668568, 0.2570429 ],
       [0.8121968 , 0.3706476 , 0.91201762],
       [0.03026532, 0.10363865, 0.2511576 ]])

In [73]:
np.random.normal(0, 6, (3, 3))


array([[-6.49984526, -9.94266745,  7.21804647],
       [ 0.14933538,  1.0476994 ,  8.02522005],
       [ 7.38708195, -2.13411579, -7.58051692]])

In [74]:
x1 = np.random.randint(90, size=29)
x1

array([57, 36, 44, 27, 77, 72, 78, 75, 89, 21, 87, 48, 59, 72, 87, 81, 86,
       23,  0, 84,  8, 11, 78, 31, 61, 53, 18, 36, 40], dtype=int32)

In [75]:
v=np.array([[[19,4,10,12],[5,7,4,19],[2,12,8,7]] ,[[19,4,10,12],[5,7,4,19],[2,12,8,7]]] )
v.ndim
v[1,1,2]

np.int64(4)

In [76]:
v=np.array([[12, 5, 2, 4], [ 7, 6, 8, 8],[ 1, 6, 7, 7]])
print(v[0:,1:2])
print(v[::-1,::-1])
v[:,0]

[[5]
 [6]
 [6]]
[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


array([12,  7,  1])

In [ ]:
v_sub_copy = v[:2, :2].copy()
print(v_sub_copy)

[[12  5]
 [ 7  6]]


In [78]:
print(v.ndim,'\n')
print(v[np.newaxis, :],'\n',(v[np.newaxis, :]).ndim,'\n') # to get and add all data in one axis basically add  them to new dimension
print(v[ : ,np.newaxis])

2 

[[[12  5  2  4]
  [ 7  6  8  8]
  [ 1  6  7  7]]] 
 3 

[[[12  5  2  4]]

 [[ 7  6  8  8]]

 [[ 1  6  7  7]]]


In [79]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],[6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [80]:
y = np.array([[99],
 [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [81]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [82]:
grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)
upper, lower = np.hsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [83]:
def recip(values):
    global order
    order=np.empty(len(values))
    for i in range(len(values)):
        order[i]=1/values[i]
    return order
values=np.random.randint(1,10,(5))
print(values)
print(recip(values))
%timeit order

[3 6 2 5 3]
[0.33333333 0.16666667 0.5        0.2        0.33333333]
36.8 ns ± 7.76 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [84]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [85]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5,np.add(x,5))
print("x - 5 =", x - 5,np.subtract(x,5))
print("x * 2 =", x * 2,np.multiply(x,2))
print("-x = ", -x,np.negative(x))
print("x ** 2 = ", x ** 2,np.power(x,2))
print("x % 2 = ", x % 2,np.mod(x,2))
x = np.array([-2, -1, 0, 1, 2])
abs(x)


x = [0 1 2 3]
x + 5 = [5 6 7 8] [5 6 7 8]
x - 5 = [-5 -4 -3 -2] [-5 -4 -3 -2]
x * 2 = [0 2 4 6] [0 2 4 6]
-x =  [ 0 -1 -2 -3] [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9] [0 1 4 9]
x % 2 =  [0 1 0 1] [0 1 0 1]


array([2, 1, 0, 1, 2])

In [86]:
np.pi

3.141592653589793

In [ ]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [88]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [89]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [90]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [91]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [92]:
x = np.arange(1, 6)
print(np.add.reduce(x))
print(np.multiply.reduce(x))
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [ ]:
np.multiply.outer(x, x)
np.add.outer(x, x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [94]:
v=np.array([[ 0.8967576 ,0.03783739 ,0.75952519, 0.06682827],
            [ 0.8354065, 0.99196818, 0.19544769, 0.43447084], 
            [ 0.66859307, 0.15038721, 0.37911423 ,0.6687194 ]])
v.sum()
# function np.prod,np.mean,np.std,np.var,np.percentile,np.any ,np.all 

np.float64(6.08505557)

In [95]:
M = np.ones((3, 3))
a = np.array([0, 1, 2])
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [96]:
x = np.linspace(0, 5, 50)
y = np.linspace(0, 5, 50)[:, np.newaxis]
z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)
print(x)
print(y)
z

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
[[0.        ]
 [0.10204082]
 [0.20408163]
 [0.30612245]
 [0.40816327]
 [0.51020408]
 [0.6122449 ]
 [0.71428571]
 [0.81632653]
 [0.91836735]
 [1.02040816]
 [1.12244898]
 [1.2244898 ]
 [1.32653061]
 [1.42857143]
 [1.53061224]
 [1.63265306]
 [1.73469388]
 [1.83673469]
 [1.93877551]
 [2.04081633]
 [2.14285714]
 [2.24489796]
 [2.34693878]
 [2.44897959]
 [2.55102041]
 [2.65306122]
 [2.75510204]
 [2.85714286]
 [2.95918367]
 [3.06122449]
 [3.16

array([[-0.83907153, -0.83470697, -0.8216586 , ...,  0.8956708 ,
         0.68617261,  0.41940746],
       [-0.83907153, -0.82902677, -0.8103873 , ...,  0.92522407,
         0.75321348,  0.52508175],
       [-0.83907153, -0.82325668, -0.79876457, ...,  0.96427357,
         0.84172689,  0.66446403],
       ...,
       [-0.83907153, -0.48233077, -0.01646558, ...,  0.96449925,
         0.75196531,  0.41982581],
       [-0.83907153, -0.47324558,  0.00392612, ...,  0.92542163,
         0.68540362,  0.37440839],
       [-0.83907153, -0.46410908,  0.02431613, ...,  0.89579384,
         0.65690314,  0.40107702]])

In [97]:
x = np.array([1, 2, 3, 4, 5])
x < 3
x > 3
x <= 3
x >= 3
x != 3 
x == 3
(2 * x) == (x ** 2)
np.equal(x,2)
np.not_equal(x,3)
np.less(x,3)
np.less_equal(x,3)
np.greater(x,3)
np.greater_equal(x,3)

array([False, False,  True,  True,  True])

In [ ]:
x = np.array([[2, 0, 0, 4],[5, 5, 6, 8], [4, 1, 4, 9]])
print(np.count_nonzero(x < 6))
print(np.sum(x < 6))
print(np.sum(x < 6, axis=1))
print(np.sum(x < 6, axis=0))
print(np.all(x < 10))
print(np.any(x > 8))
np.all(x < 8, axis=1)

9
9
[4 2 3]
[3 3 2 1]
True
True


array([ True, False, False])

In [99]:
x[x < 5]

array([2, 0, 0, 4, 4, 1, 4])

In [100]:
bin(32) 
print(bool(42 and 0))
print(bool(42 or 0)) 
print(bin(42))
print(bin(59))
print(bin(42 & 59))  
bin(42 | 59)

False
True
0b101010
0b111011
0b101010


'0b111011'

In [101]:
x = np.arange(10)
print( np.sum((x > 4))) 
print(np.count_nonzero( (x < 3)))
ind = [3, 7, 4] 
print(x[ind])
ind = np.array([[3, 7],[4, 5]])
x[ind]

5
3
[3 7 4]


array([[3, 7],
       [4, 5]])

In [102]:
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print(X[row, col])
X[2, [2, 0, 1]]

[ 2  5 11]


array([10,  8,  9])

In [103]:
 row[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

In [ ]:
mask = np.array([1, 0, 1, 0], dtype=bool) 
print(mask)
print(row[:, np.newaxis])
X[row[:, np.newaxis], mask]

[ True False  True False]
[[0]
 [1]
 [2]]


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [105]:
i = [2, 3, 3, 4, 4, 4] 
x = np.zeros(10)
np.add.at(x, i, 1)
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


In [106]:
np.random.seed(42)
x = np.random.randn(100)
print(x)
bins = np.linspace(-5, 5, 20)
counts = np.zeros_like(bins)
print(bins)
i = np.searchsorted(bins, x)
i

[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975
  0.24196227 -1.91328024 -1.72491783 -0.56228753 -1.01283112  0.31424733
 -0.90802408 -1.4123037   1.46564877 -0.2257763   0.0675282  -1.42474819
 -0.54438272  0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375
 -0.60170661  1.85227818 -0.01349722 -1.05771093  0.82254491 -1.22084365
  0.2088636  -1.95967012 -1.32818605  0.19686124  0.73846658  0.17136828
 -0.11564828 -0.3011037  -1.47852199 -0.71984421 -0.46063877  1.05712223
  0.34361829 -1.76304016  0.32408397 -0.38508228 -0.676922    0.61167629
  1.03099952  0.93128012 -0.83921752 -0.30921238  0.33126343  0.97554513
 -0.47917424 -0.18565898 -1.10633497 -1.19620662  0.81252582  1.35624003
 -0.07201012  1.0035329   0.36163603 -0.64511975  0.36139561  1.53803657
 -0.03582604  1.56464366 -2.6197451   0.8219025   0.08704707 -0.29900735
  0.09176078 -1.98756891 -0.21967189  0.35711257  1

array([11, 10, 11, 13, 10, 10, 13, 11,  9, 11,  9,  9, 10,  6,  7,  9,  8,
       11,  8,  7, 13, 10, 10,  7,  9, 10,  8, 11,  9,  9,  9, 14, 10,  8,
       12,  8, 10,  6,  7, 10, 11, 10, 10,  9,  7,  9,  9, 12, 11,  7, 11,
        9,  9, 11, 12, 12,  8,  9, 11, 12,  9, 10,  8,  8, 12, 13, 10, 12,
       11,  9, 11, 13, 10, 13,  5, 12, 10,  9, 10,  6, 10, 11, 13,  9,  8,
        9, 12, 11,  9, 11, 10, 12,  9,  9,  9,  7, 11, 10, 10, 10])